import Navbar from "./(components)/Nav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata = {
  title: "Next Ticketing App",
  description: "Generated by Muhammad Suleman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-scren">
          <Navbar />
          <div className="flex-grow overflow-y-auto bg-page text-defaultText">{children}</div>
        </div>
      </body>
    </html>
  );
}
